import type { Metadata } from "next";
import "./globals.css";
import TaskBar from "@/modules/core/components/TaskBar";
import Workspace from "@/modules/core/components/Workspace";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`h-screen bg-gradient-to-r from-cyan-500 to-blue-500`}
      >
        {children}
        <Workspace />
        <TaskBar />
      </body>
    </html>
  );
}
